---                                                                                                                     
- hosts: mineservers
  vars_files:
  - ./vars.yml
  tasks:
  - name: Run apt-update
    apt:
      update_cache: yes
      
  - name: Install packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl 
      - gnupg2
      - software-properties-common
      - python-pip
      - python-pkg-resources
      - python-setuptools
      
  - name: Add docker key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
      
  - name: Add docker official repository for Debian Stretch
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
      state: present
      
  - name: Index new repo into the cache
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes
      
  - name: Install docker
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      
  - name: Install docker-pip
    pip:
      name: 
      - setuptools
      - docker
      
  - name: Ensure group "docker" exists
    group:
      name: docker
      state: present
      
  - name: Add new user 'mine', who can access docker
    user:
      uid: "{{ user_uid }}"
      shell: /bin/bash
      name: mine
      append: yes
      create_home: true
      state: present

  - name: Create data directory
    file:
      path: /home/mine/data
      state: directory
      owner: mine

  - name: Create anisble tmp directory
    file:
      path: /home/mine/.ansible/tmp
      mode: "0700"
      state: directory
      owner: mine
      
  - name: Copy data
    copy:
      src: ./data/
      dest: /home/mine/data/
      owner: mine
      
  - name: Start Minecraft
    docker_container:
      name: mc
      image: itzg/minecraft-server
      env: 
        EULA: "TRUE"
        UID: "{{ user_uid }}"
        SERVER_PORT: "{{ server_port }}"
        MEMORY: "{{ server_memory }}"
      ports:
       - "{{ server_port }}:{{ server_port }}"
      volumes:
       - "/home/mine/data:/data"
    become_user: mine